#+title: Break 42 Eggs

A multiplayer console based game where players join the server and compete to break the most eggs. The game is played in rounds, each round lasts infinitely. The player who breaks the most eggs three days after easter wins. The game will shut down after.

* How it works
  Once a user joins the server they have one egg and 9 points available. 
  the user is not aware of the strength of the egg. The user can break the egg with another user.

  - The user with the stronger egg wins and gets 6 points.
  - The loser loses 3 points and has no egg. so he needs to buy an egg to play again. An egg costs 3 points.
  - If both users break one side of the egg each then they both gain 3 points and loose the egg.


* How to host your own server
  Download this repository and run the server by running the following command in the terminal:
  #+begin_src shell
  > python3 break42.py server <port:12345>
  #+end_src

* How to use it on the 42 server
  Download this repository and run the client by running the following command in the terminal:
  #+begin_src shell
  > python3 break42.py eggs.42.mk
  #+end_src

* Client Commands
  - There are just four commands that the client can use:
    - buy - Buy an egg
    - list - leaderboard
    - break <user> - Break an egg with a user
    - quit - Quit the game

  


